# Generated by Django 5.0 on 2024-04-10 05:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Disruptor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("category", models.CharField(max_length=200)),
            ],
            options={
                "verbose_name": "disruptor",
                "verbose_name_plural": "disruptor",
            },
        ),
        migrations.AlterModelOptions(
            name="organization",
            options={
                "verbose_name": "organization",
                "verbose_name_plural": "organization",
            },
        ),
    ]
