# Generated by Django 5.0 on 2024-04-10 07:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0003_rename_name_disruptor_affected_aspect"),
    ]

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("title", models.CharField(max_length=100)),
                ("university", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="team_images")),
            ],
        ),
    ]
