# Generated by Django 5.0 on 2024-04-10 07:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0005_alter_team_options_alter_team_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="image",
            field=models.ImageField(upload_to="static/images"),
        ),
    ]
