# Generated by Django 5.0 on 2024-04-25 06:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0006_alter_team_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("regNo", models.CharField(max_length=100)),
                ("fName", models.CharField(max_length=100)),
                ("sName", models.CharField(max_length=100)),
                ("lName", models.CharField(max_length=100)),
                ("academic_level", models.CharField(max_length=100)),
                ("program", models.CharField(max_length=100)),
                ("year", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Students",
                "verbose_name_plural": "Students",
            },
        ),
        migrations.AlterModelOptions(
            name="disruptor",
            options={"verbose_name": "disruptor", "verbose_name_plural": "disruptors"},
        ),
        migrations.AlterModelOptions(
            name="team",
            options={
                "verbose_name": "Team Members",
                "verbose_name_plural": "Team Members",
            },
        ),
    ]
