# Generated by Django 5.0 on 2024-04-25 06:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0007_student_alter_disruptor_options_alter_team_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Employees",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("empId", models.CharField(max_length=100)),
                ("fName", models.CharField(max_length=100)),
                ("sName", models.CharField(max_length=100)),
                ("lName", models.CharField(max_length=100)),
                ("department", models.CharField(max_length=100)),
                ("orgName", models.CharField(max_length=100)),
                ("professional", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Employees",
                "verbose_name_plural": "Employees",
            },
        ),
    ]
