# Generated by Django 5.0 on 2024-06-07 07:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0008_employees"),
    ]

    operations = [
        migrations.CreateModel(
            name="Facilities",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("classrooms", models.CharField(max_length=100)),
                ("library", models.CharField(max_length=100)),
                ("laboratory", models.CharField(max_length=100)),
                ("accomodation", models.CharField(max_length=100)),
                ("playgrounds", models.CharField(max_length=100)),
                ("online_resources", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Facilities",
                "verbose_name_plural": "Facilities",
            },
        ),
    ]
