# Generated by Django 5.0 on 2024-06-08 18:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0011_alter_facilities_classrooms_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Finance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("budget", models.CharField(max_length=100)),
                ("tuition_fee", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Finance",
                "verbose_name_plural": "Finance",
            },
        ),
        migrations.RemoveField(
            model_name="academic",
            name="facilities",
        ),
        migrations.AlterField(
            model_name="academic",
            name="college",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="academic",
            name="enrollement_rate",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="academic",
            name="programs",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="facilities",
            name="accomodation",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
