# Generated by Django 5.0 on 2024-06-08 18:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0012_finance_remove_academic_facilities_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Administrative",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("policy", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Administrative",
                "verbose_name_plural": "Administrative",
            },
        ),
    ]
