# Generated by Django 5.0 on 2024-06-08 18:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0013_administrative"),
    ]

    operations = [
        migrations.CreateModel(
            name="Social",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sport", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Social",
                "verbose_name_plural": "Social",
            },
        ),
    ]
