# Generated by Django 5.0 on 2024-06-09 14:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0015_facilities_college"),
    ]

    operations = [
        migrations.AlterField(
            model_name="facilities",
            name="college",
            field=models.CharField(max_length=100),
        ),
    ]
