# Generated by Django 5.0 on 2024-06-09 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0016_alter_facilities_college"),
    ]

    operations = [
        migrations.AlterField(
            model_name="facilities",
            name="college",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="website.academic"
            ),
        ),
    ]
