# Generated by Django 5.0 on 2024-06-09 15:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0017_alter_facilities_college"),
    ]

    operations = [
        migrations.RenameField(
            model_name="academic",
            old_name="enrollement_rate",
            new_name="enrollment_rate",
        ),
        migrations.AlterField(
            model_name="academic",
            name="college",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="academic",
            name="programs",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="facilities",
            name="accomodation",
            field=models.CharField(max_length=100),
        ),
    ]
