# Generated by Django 5.0 on 2024-06-09 15:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0018_rename_enrollement_rate_academic_enrollment_rate_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="facilities",
            name="college",
        ),
        migrations.AddField(
            model_name="facilities",
            name="collegeF",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
