# Generated by Django 5.0 on 2024-06-09 15:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0020_remove_facilities_collegef_facilities_college"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="facilities",
            name="college",
        ),
        migrations.AddField(
            model_name="facilities",
            name="collegeF",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
