# Generated by Django 5.0 on 2024-06-09 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0023_finance_college"),
    ]

    operations = [
        migrations.AddField(
            model_name="finance",
            name="programs",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="program_finances",
                to="website.academic",
            ),
        ),
        migrations.AlterField(
            model_name="finance",
            name="college",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="college_finances",
                to="website.academic",
            ),
        ),
    ]
