# Generated by Django 5.0 on 2024-06-09 18:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0024_finance_programs_alter_finance_college"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="finance",
            name="budget",
        ),
    ]
