# Generated by Django 5.0 on 2024-06-09 19:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0025_remove_finance_budget"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="finance",
            name="programs",
        ),
        migrations.AddField(
            model_name="finance",
            name="program",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
