# Generated by Django 5.0 on 2024-06-09 20:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0026_remove_finance_programs_finance_program"),
    ]

    operations = [
        migrations.AddField(
            model_name="facilities",
            name="health_facilities",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
