# Generated by Django 5.0 on 2024-06-16 21:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0027_facilities_health_facilities"),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("file", models.FileField(upload_to="documents/")),
            ],
        ),
    ]
