# Generated by Django 5.0.7 on 2024-07-15 12:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0029_alter_document_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="link",
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="document",
            name="file",
            field=models.FileField(
                blank=True, max_length=255, null=True, upload_to="documents/"
            ),
        ),
    ]
